### ISSUE TITLE
what is ? 

### ISSUE THREAD

**Issue by SarnaxLii** [Span0/cleaner#1]
What is it and how does it work? My suspicion is your website links. How does it benefit?

**Comment by Span0** [comment]
You mean firehol.org? I'm not affiliated to them, they are well know and maintain some of the best free ip blocklist (more info are available on their website : https://iplists.firehol.org/ ).

This repository serve no other purpose than removing some ip's from their blacklist to avoid issue on a test environement and also provide blocklist based on some compagny ASN ip range.

**Comment by SarnaxLii** [comment]
ok thanks you , It's helpful, I'll clone it for the future.

**Comment by SarnaxLii** [comment]
Are you BOT ? Why is there too much work?

**Comment by Span0** [comment]
I'm using a cron to update all blocklist hourly to track thoses blocklist history.
Yea it messup my commit numbers but thoses are very useful datas i'm using for daily/weekly/montly/yearly analysis/stats on the blocked ip's from thoses lists. I will publish later this year my analysis, but it's far from complete.

**Comment by SarnaxLii** [comment]
Ok

**Comment by Santiagocostaa** [comment]
Help guys [SarnaxLii](https://github.com/SarnaxLii) He is a scammer , he robbed me , I paid for a spoofer he deleted everything after receiving the money , waited 1 day and deleted me

**Comment by SarnaxLii** [comment]
Show me proof when I cheated on you idiot. Your account was created a day or two ago, that's funny.

**Comment by SarnaxLii** [comment]
@Span0  please delete lssues
